from typing import Optional, Union, Dict, Any
from fastapi import APIRouter, Depends, Body
from sqlalchemy.orm import Session

from pydantic import ValidationError
from app.database import get_db
from app.config import settings
from app.models.user import LearnerProfile
from app.models.plan import LearningPlan, LearningPlanStep
from app.schemas.common import StandardEnvelope
from app.schemas.plan import PlanCreate, PlanResponse, PlanStepResponse
from app.utils.exceptions import ResourceNotFoundException, ValidationException

router = APIRouter(tags=["AI Learning Planner"])

def _serialize_plan(plan: LearningPlan) -> PlanResponse:
    steps_data = [
        PlanStepResponse(
            id=step.id,
            skill=step.skill,
            topic=step.topic,
            duration_minutes=step.duration_minutes,
            practice=step.practice,
            evidence=step.evidence,
            priority=step.priority,
        )
        for step in plan.steps
    ]
    return PlanResponse(
        id=plan.id,
        user_id=plan.user_id,
        plan_title=plan.plan_title,
        reason=plan.reason,
        created_at=plan.created_at.isoformat() if plan.created_at else None,
        steps=steps_data,
    )

@router.post("/v1/planner/plan", response_model=StandardEnvelope[PlanResponse])
def persist_learning_plan(
    payload: Union[PlanCreate, Dict[str, Any]] = Body(...),
    db: Session = Depends(get_db)
):
    """
    Validates and persists a personalized Next Learning Plan generated by the AI Planner.
    Associates the plan with the authenticated learner.
    Does NOT modify readiness, skill scores, or roadmap state.
    """
    # Support payload passed either directly or wrapped inside {"plan": ...}
    try:
        if isinstance(payload, dict):
            if "plan" in payload and isinstance(payload["plan"], dict):
                plan_in = PlanCreate(**payload["plan"])
            else:
                plan_in = PlanCreate(**payload)
        else:
            plan_in = payload
    except ValidationError as ve:
        raise ValidationException(str(ve))


    profile = db.query(LearnerProfile).filter(LearnerProfile.user_id == settings.DEFAULT_USER_ID).first()
    if not profile:
        raise ResourceNotFoundException("Learner profile not found.")

    # Time constraint validation: total duration <= learner's weekly commitment
    weekly_hours = profile.weekly_commitment_hours or 12
    max_minutes = weekly_hours * 60
    total_minutes = sum(step.duration_minutes for step in plan_in.steps)
    if total_minutes > max_minutes:
        raise ValidationException(
            f"Planner generated {total_minutes} minutes, but learner has only {max_minutes} minutes available this week."
        )

    # Persist the plan
    new_plan = LearningPlan(
        user_id=profile.user_id,
        plan_title=plan_in.plan_title,
        reason=plan_in.reason,
    )
    db.add(new_plan)
    db.flush()

    for idx, step in enumerate(plan_in.steps, start=1):
        step_entry = LearningPlanStep(
            plan_id=new_plan.id,
            step_order=idx,
            skill=step.skill,
            topic=step.topic,
            duration_minutes=step.duration_minutes,
            practice=step.practice,
            evidence=step.evidence,
            priority=step.priority,
        )
        db.add(step_entry)

    db.commit()
    db.refresh(new_plan)

    return StandardEnvelope(data=_serialize_plan(new_plan))

@router.get("/v1/planner/plan/latest", response_model=StandardEnvelope[Optional[PlanResponse]])
@router.get("/v1/planner/plan", response_model=StandardEnvelope[Optional[PlanResponse]])
def get_latest_learning_plan(db: Session = Depends(get_db)):
    """
    Retrieves the most recent AI-generated learning plan for the learner.
    """
    latest_plan = (
        db.query(LearningPlan)
        .filter(LearningPlan.user_id == settings.DEFAULT_USER_ID)
        .order_by(LearningPlan.created_at.desc())
        .first()
    )

    if not latest_plan:
        return StandardEnvelope(data=None)

    return StandardEnvelope(data=_serialize_plan(latest_plan))
